name: Azure GA Web App - Production Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'github-deployment/**' ]

env:
  AZURE_WEBAPP_NAME: GA
  AZURE_RESOURCE_GROUP: GA_group
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Create deployment package
      run: |
        cd github-deployment
        echo "Preparing GA Flask app deployment..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Azure GA Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './github-deployment'
