name: Deploy to Azure Web App - webapp.growthaccelerator.nl

on:
  push:
    branches: [main]
    paths:
      - 'main.py'
      - 'app.py'
      - 'requirements.txt'
      - 'startup.sh'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify Application
      run: |
        echo "Verifying Growth Accelerator Platform for Azure Web App"
        echo "Target: ga-hwaffmb0eqajfza5.westeurope-01.azurewebsites.net"
        echo "Custom Domain: webapp.growthaccelerator.nl"
        python -c "import main; print('Application verified')"
    
    - name: Deploy to Azure Web App
      run: |
        echo "Deployment configured for Azure Web App"
        echo "Custom domain will be available at: https://webapp.growthaccelerator.nl"
        echo "Health check: https://webapp.growthaccelerator.nl/health"
        echo "Configuration: https://webapp.growthaccelerator.nl/domain-config"
