name: Azure ZIP Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create ZIP package
      run: |
        cd github-deployment
        zip -r ../app.zip .
        
    - name: Deploy via ZIP
      run: |
        curl -X POST -u '${{ secrets.AZURE_DEPLOYMENT_USERNAME }}:${{ secrets.AZURE_DEPLOYMENT_PASSWORD }}' \
        -T ../app.zip \
        https://ga-hwaffmb0eqajfza5.scm.westeurope-01.azurewebsites.net/api/zipdeploy
