name: Azure Direct Health Fix

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd github-deployment
        pip install -r requirements.txt
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ga-hwaffmb0eqajfza5
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: github-deployment
