name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [ main ]
    paths:
      - 'static_build/**'
  workflow_dispatch:

jobs:
  deploy_static_apps:
    runs-on: ubuntu-latest
    name: Deploy Static Landing Pages
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Deploy to thankful-moss
        id: deploy-thankful
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/static_build"
          output_location: ""
          skip_app_build: true
      
      - name: Deploy to white-coast
        if: success()
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_COAST || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/static_build"
          output_location: ""
          skip_app_build: true