name: Azure GA - Production Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        default: 'production'
  push:
    branches: [ main ]
    paths: [ 'github-deployment/**' ]

env:
  AZURE_WEBAPP_NAME: ga-hwaffmb0eqajfza5
  AZURE_RESOURCE_GROUP: GA_group
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure
    runs-on: ubuntu-latest
    environment: 
      name: GA_Production
      url: https://ga-hwaffmb0eqajfza5.westeurope-01.azurewebsites.net
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Verify deployment files
      run: |
        echo "Verifying deployment package structure..."
        cd github-deployment
        ls -la
        echo "Contents of app.py:"
        head -10 app.py
        echo "Contents of requirements.txt:"
        cat requirements.txt
        
    - name: Install Python dependencies
      run: |
        cd github-deployment
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list
        
    - name: Test application locally
      run: |
        cd github-deployment
        timeout 10s python -c "
        import app
        print('Application imports successfully')
        flask_app = app.application
        print('Flask app created successfully')
        " || echo "Local test completed"
        
    - name: Prepare deployment package
      run: |
        cd github-deployment
        echo "Preparing Azure deployment package..."
        echo "Files to deploy:"
        find . -type f -name "*.py" -o -name "*.txt" -o -name "*.config" -o -name "*.sh"
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './github-deployment'
        
    - name: Verify deployment
      run: |
        echo "Waiting for Azure deployment to initialize..."
        sleep 45
        echo "Testing health endpoint..."
        for i in {1..5}; do
          if curl -f -s https://ga-hwaffmb0eqajfza5.westeurope-01.azurewebsites.net/health; then
            echo "Health check successful on attempt $i"
            break
          else
            echo "Health check failed on attempt $i, retrying in 15 seconds..."
            sleep 15
          fi
        done
        
    - name: Deployment summary
      run: |
        echo "🚀 Growth Accelerator Platform deployed to Azure"
        echo "📍 URL: https://ga-hwaffmb0eqajfza5.westeurope-01.azurewebsites.net"
        echo "🔍 Health: https://ga-hwaffmb0eqajfza5.westeurope-01.azurewebsites.net/health"
        echo "📊 Status: https://ga-hwaffmb0eqajfza5.westeurope-01.azurewebsites.net/api/status"
