name: "[DISABLED] azure-static-web-apps.yml"

# This workflow has been disabled to prevent deployment conflicts
# Only azure-ga-webapp.yml and azure-custom-domain.yml should be active

on:
  # Disabled to prevent conflicts - use azure-ga-webapp.yml instead
  workflow_dispatch:
    inputs:
      force_enable:
        description: 'Force enable this disabled workflow'
        required: false
        default: 'false'

jobs:
  disabled_notice:
    if: github.event.inputs.force_enable == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Disabled Notice
        run: |
          echo "This workflow has been disabled to prevent deployment conflicts"
          echo "Active workflows: azure-ga-webapp.yml, azure-custom-domain.yml"
          echo "Original workflow: azure-static-web-apps.yml"
