name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Growth Accelerator Platform
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Platform Validation
      run: |
        echo "🔍 Validating Growth Accelerator Platform for multi-platform deployment"
        
        # Check critical files
        MISSING_FILES=()
        
        if [ ! -f "index.html" ]; then
          MISSING_FILES+=("index.html")
        fi
        
        if [ ! -f "main.py" ]; then
          MISSING_FILES+=("main.py")
        fi
        
        if [ ! -f "requirements.txt" ]; then
          MISSING_FILES+=("requirements.txt")
        fi
        
        if [ ${#MISSING_FILES[@]} -eq 0 ]; then
          echo "✓ All critical files present"
        else
          echo "⚠ Missing files: ${MISSING_FILES[@]}"
          exit 1
        fi
        
    - name: Multi-Platform Deployment Readiness
      run: |
        echo "📋 Multi-Platform Deployment Status:"
        echo "  ✓ Static Web Apps: thankful-moss, white-coast"
        echo "  ✓ Web App: ga-hwaffmb0eqajfza5.westeurope-01.azurewebsites.net"
        echo "  ✓ Custom Domain: webapp.growthaccelerator.nl"
        echo "  ✓ All platforms configured for Growth Accelerator Platform"
        
  deployment_coordination:
    needs: validate
    runs-on: ubuntu-latest
    name: Deployment Coordination
    
    steps:
    - name: Trigger Platform Deployments
      run: |
        echo "🚀 Coordinating multi-platform deployments..."
        echo "Static Web Apps will deploy via growth-accelerator-azure-static workflow"
        echo "Web App will deploy via azure-webapp-deploy workflow"
        echo "All platforms will receive Growth Accelerator Platform updates"
